project:
  type: website
  output-dir: docs
website:
  page-navigation: true
  title: "Grade Predictor"
  page-footer:
    background: "#C8102E"
    center: "Created by: Venkata Surya Vineel Nekkanti"

  navbar:
     background: "#C8102E"
     center: "Grade Predictor"
     pinned: true
     align: centre
     style: docked

format:
  html:
    theme:
      light: sketchy
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    code-link: true
    css: styles.css
  
execute:
  freeze: auto

editor: visual